name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: Check, Lint, Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "1.95.0"
          components: rustfmt, clippy

      - name: Install cargo-nextest, cargo-deny and cargo-audit
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest,cargo-deny,cargo-audit

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Check
        run: cargo check --workspace

      - name: Format
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --workspace -- -D warnings

      - name: Deny
        run: cargo deny check

      - name: Audit
        run: cargo audit

      - name: Test
        run: cargo nextest run --workspace --no-tests=pass